DOCSP-42321: Insert landing page
mongodb/docs-scala pull request #55
Opened 2024-10-14 16:06 UTC by mcmorisi

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-scala/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-42321>
Staging - <https://deploy-preview-55--docs-scala.netlify.app/write/>

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?
- [x] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-10-14 19:15 UTC, rustagir approved these changes
lgtm with a few small improvements!

2024-10-14 19:15 UTC, rustagir commented on source/write.txt
> +can use to write data to MongoDB with the {+driver-short+}.
```suggestion
can use to write data to MongoDB by using the {+driver-short+}.
```

2024-10-14 19:15 UTC, rustagir commented on source/includes/usage-examples/WriteCodeExamples.scala
> +    val filter = equal("<field to match>", "<value to match>")
S: reverse the order of these two lines

2024-10-14 19:17 UTC, mcmorisi commented on source/write.txt
> +can use to write data to MongoDB with the {+driver-short+}.
Every time, this one gets me!

2024-10-17 10:13 UTC, rozza requested changes

2024-10-17 10:13 UTC, rozza commented on source/includes/usage-examples/SampleWriteApp.scala
> +    // Wait for the operations to complete before closing client
```suggestion
    // Wait for the operations to complete before closing client
    // Note: This example uses `Thread.sleep` for brevity 
    // this does not guarantee all operations will be completed in time.
```

I think its important to note to users the sleep provides no guarantees.

2024-10-17 13:11 UTC, rozza approved these changes
LGTM

2024-10-17 13:13 UTC, merged