DOCSP-42328: Specify a query
mongodb/docs-scala pull request #57
Opened 2024-10-14 21:03 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-scala/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-10-15 14:17 UTC, jordan-smith721 approved these changes
Nice work! LGTM

2024-10-15 14:17 UTC, jordan-smith721 commented on source/read/specify-a-query.txt
> +To learn more about any of the methods or types discussed in this
```suggestion
To learn more about any of the methods discussed in this
```

2024-10-17 10:15 UTC, rozza requested changes

2024-10-17 10:15 UTC, rozza commented on source/includes/read/specify-queries.scala
> +    collection.insertMany(fruits)
This doesn't do anything apart from create an `Observable` it must be subscribed to, to actually write some data.

2024-10-18 08:45 UTC, rozza approved these changes
LGTM

2024-10-18 14:34 UTC, merged