DOCSP-42340 Multikey Index
mongodb/docs-scala pull request #76
Opened 2024-10-25 23:29 UTC by lindseymoore

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-scala/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-42340>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-10-28 19:12 UTC, jordan-smith721 approved these changes
One suggestion + one typo fix but otherwise LGTM!

2024-10-28 19:12 UTC, jordan-smith721 commented on source/indexes/multikey-index.txt
> +You can verify that the index was created by using the ``listIndexes()`` method.
```suggestion
You can verify that the index was created by calling the ``listIndexes()`` method.
```

2024-10-28 19:12 UTC, jordan-smith721 commented on source/indexes/multikey-index.txt
> +To learn more about compound indexes, see :manual:`Multikey
```suggestion
To learn more about multikey indexes, see :manual:`Multikey
```

2024-11-05 15:14 UTC, jyemin requested changes
Please, please, please compile and run all the code before putting it up for review.  I got lucky spotting this error (I'm not a very good compiler!).

2024-11-05 15:14 UTC, jyemin commented on source/includes/indexes/multikey-field.scala
> +import org.mongodb.scala.model.Projections._
Lots of these imports are unused

2024-11-14 20:50 UTC, lindseymoore commented on source/includes/indexes/multikey-field.scala
> +import org.mongodb.scala.model.Projections._
Thanks! Removed projections and sorts

2024-11-14 20:50 UTC, lindseymoore commented on source/includes/indexes/multikey-field.scala
> +    val filter1 = and(equal("cast", "Aamir Khan"), equal("cast", "Kajol"))
Thank you, fixed!

2024-11-14 20:58 UTC, mcmorisi approved these changes
LGTM!

2024-11-19 20:35 UTC, merged