DOCSP-42316: Stable API
mongodb/docs-scala pull request #81
Opened 2024-11-05 18:42 UTC by mcmorisi

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-scala/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-11-05 19:46 UTC, norareidy approved these changes
LGTM with some suggestions

2024-11-05 19:46 UTC, norareidy commented on source/connect/stable-api.txt
> +#. Construct a ``MongoClientSettings`` object using the ``MongoClientSettings.Builder`` class.
S: [by using](https://www.mongodb.com/docs/meta/style-guide/terminology/alphabetical-terms/#std-term-using)
```suggestion
#. Construct a ``MongoClientSettings`` object by using the ``MongoClientSettings.Builder`` class.
```

2024-11-05 19:46 UTC, norareidy commented on source/connect/stable-api.txt
> +a specified API version, all commands you run with the client use the specified
S: add "that"
```suggestion
a specified API version, all commands that you run with the client use the specified
```

2024-11-05 19:46 UTC, norareidy commented on source/connect/stable-api.txt
> +parameters to customize the behavior of the {+stable-api+}.
S: I'm not sure if "parameters" is the best word for these. Maybe "options" that you can set by calling methods from the ServerApi class?
```suggestion
The following table describes {+stable-api+} options that you can set by calling methods from the ``ServerApi`` class. You can use these
options to customize the behavior of the {+stable-api+}.
```

2024-11-05 19:46 UTC, norareidy commented on source/connect/stable-api.txt
> +#. Instantiate a ``MongoClient`` using the ``MongoClient.create()`` method and
S: the code example doesn't use the create() method, so I'd just say the constructor
```suggestion
#. Instantiate a ``MongoClient`` using the constructor and 
```

2024-11-05 22:47 UTC, jyemin requested changes
One suggestion, but LGTM

2024-11-05 22:47 UTC, jyemin commented on source/connect/stable-api.txt
> +option to ``False`` when constructing your ``ServerApi`` object.
```suggestion
option to ``false`` when constructing your ``ServerApi`` object.
```

2024-11-06 13:43 UTC, jyemin approved these changes

2024-11-06 14:53 UTC, merged